-- Enable Row Level Security (RLS) on tables in `public` schema.
--
-- Why: Supabase exposes `public` schema tables via PostgREST. If RLS is disabled,
-- the linter flags them as externally exposed (and sensitive columns may be reachable).
--
-- Note: We only ENABLE RLS (no policies). Default behavior becomes DENY for roles
-- subject to RLS (e.g. `anon`, `authenticated`). Server-side connections using the
-- DB owner / service role are typically unaffected.

ALTER TABLE IF EXISTS public."Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VerificationToken" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."Questionnaire" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Topic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."LegalDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TemaOficial" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StudyStreak" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Solution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SpacedRepetitionCard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StudySession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SystemError" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UserAchievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MarkedQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AllowedPhoneNumber" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ClassroomParticipant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UserAnswer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."QuestionnaireAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ForumPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Achievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ExamSimulation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DocumentSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VirtualClassroom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ClassSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ForumThread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GeneratedQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TemaArchivo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TemaLegalDocument" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.tema_archivo_blobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_registration_meta ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."FailedLoginAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AppSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."BackupLog" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."RepoDocumentAccessLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RepoAccessRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RepoFolder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RepoDocument" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."BoeMonitorRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."BoeAlertItem" ENABLE ROW LEVEL SECURITY;
